spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.199.129:3307/jdbc?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver

    initialization-mode: always

    schema:
      - classpath:department.sql
